// constants for Home page posters
export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_ERROR = "FETCH_MOVIES_ERROR";

// On-click to get Movie Details
export const FETCH_MOVIE_DETAIL_REQUEST = "FETCH_MOVIE_DETAIL_REQUEST";
export const FETCH_MOVIE_DETAIL_SUCCESS = "FETCH_MOVIE_DETAIL_SUCCESS";
export const FETCH_MOVIE_DETAIL_ERROR = "FETCH_MOVIE_DETAIL_ERROR"

// On-click to get person Details
export const FETCH_PERSON_DETAIL_REQUEST = "FETCH_PERSON_DETAIL_REQUEST"
export const FETCH_PERSON_DETAIL_SUCCESS = "FETCH_PERSON_DETAIL_SUCCESS"
export const FETCH_PERSON_DETAIL_ERROR = "FETCH_PERSON_DETAIL_ERROR"

// Create Session Id for the TMDB user Authentication 
export const FETCH_USER_SESSION_ID_REQUEST = "FETCH_USER_SESSION_ID_REQUEST"
export const FETCH_USER_SESSION_ID_SUCCESS = "FETCH_USER_SESSION_ID_REQUEST"
export const FETCH_USER_SESSION_ID_ERROR = "FETCH_USER_SESSION_ID_REQUEST"
